version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ${VOLUME_PATH}:/var/lib/postgresql/data
